name: flutter_apple_llm
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAppleLlmPlugin
